name: "Release a tag"

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Create release
        id: goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update install links
        run: |
            wget -q https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O jq
            chmod +x ./jq
            echo "======"
            echo '${{steps.goreleaser.outputs.artifacts}}' | ./jq '.[] | select((.goos=="linux") and (.type=="Archive")) | {name}'
            echo "======"
            tag=$(echo '${{steps.goreleaser.outputs.metadata}}' | ./jq '.tag')
            echo "===${tag}==="
