name: "Release a tag"

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Create release
        id: goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update install links
        run: |
            wget -q https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O jq
            chmod +x ./jq
            tag=$(echo '${{steps.goreleaser.outputs.metadata}}' | ./jq --raw-output '.tag')
            linux_name=$(echo '${{steps.goreleaser.outputs.artifacts}}' | ./jq --raw-output '.[] | select((.goos=="linux") and (.type=="Archive")) | .name')
            mac_name=$(echo '${{steps.goreleaser.outputs.artifacts}}' | ./jq --raw-output '.[] | select((.goos=="darwin") and (.type=="Archive")) | .name')
            windows_name='$(echo ${{steps.goreleaser.outputs.artifacts}}' | ./jq --raw-output '.[] | select((.goos=="windows") and (.type=="Archive")) | .name')
            echo "===https://github.com/Enapter/enapter-cli/releases/download/${tag}/${linux_name}==="
            echo "===https://github.com/Enapter/enapter-cli/releases/download/${tag}/${mac_name}==="
            echo "===https://github.com/Enapter/enapter-cli/releases/download/${tag}/${windows_name}==="
